force-app/main/default/objects/OpenAISettings__c/OpenAISettings__c.object-meta.xml
<CustomObject>
    <label>OpenAISettings</label>
    <nameField>
        <label>OpenAI Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpenAISettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenAISettings__c/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>/v1/completions</fullName>
                <default>true</default>
                <label>/v1/completions</label>
            </value>
            <value>
                <fullName>/v1/chat/completions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/LengthOfDaysToKeepHistory__c.field-meta.xml
<CustomField>
    <fullName>LengthOfDaysToKeepHistory__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Length Of Days To Keep History</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/MaxTokenSize__c.field-meta.xml
<CustomField>
    <fullName>MaxTokenSize__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>Max Token Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BaseURL__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text-davinci-003</fullName>
                <default>true</default>
                <label>text-davinci-003</label>
            </value>
            <value>
                <fullName>text-davinci-002</fullName>
            </value>
            <value>
                <fullName>text-curie-001</fullName>
            </value>
            <value>
                <fullName>text-babbage-001</fullName>
            </value>
            <value>
                <fullName>text-ada-001</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-0613</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k-0613</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Temperature</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChatGPTSettingsHandler.cls
/****** BEGIN LICENSE BLOCK *****
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
The Initial Developer of the Original Code is Amberteq Inc.
Portions created by the Initial Developer are Copyright (C) 2023
the Initial Developer. All Rights Reserved.
***** END LICENSE BLOCK ******/

public with sharing class ChatGPTSettingsHandler {
    
    /**
     * This method retrieves the settings from the OpenAISettings__c object
     * and returns it as an OpenAISettings__c object. 
     * If no settings are found, it creates a default settings object and inserts it.
     * @param userId String with user Id
     * @return OpenAISettings__c record
     */
    @AuraEnabled 
    public static OpenAISettings__c getSettings(String userId){
        try {
            List<OpenAISettings__c> settings = new List<OpenAISettings__c>();

            settings = [
                SELECT Id, Name, BaseURL__c, Model__c, Temperature__c, MaxTokenSize__c, LengthOfDaysToKeepHistory__c
                FROM OpenAISettings__c 
                WHERE OwnerId = :userId
            ];

            if (settings.isEmpty()) {
                settings.add(new OpenAISettings__c(
                    Name = 'Settings', 
                    BaseURL__c = '/v1/chat/completions', 
                    Model__c = 'gpt-4',
                    MaxTokenSize__c = 1000,
                    Temperature__c = 0,
                    LengthOfDaysToKeepHistory__c = 3
                ));
                insert settings;
            }
            return settings[0];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * This method takes a JSON string as a parameter and
     * deserializes it into an OpenAISettings__c object. 
     * It then updates the object with the new values.
     * @param settingsItemJSON String with JSON OpenAiSettings__c record
     */
    @AuraEnabled
    public static void updateSettings(String settingsItemJSON){
        try {
            OpenAISettings__c settingsItem = (OpenAISettings__c) JSON.deserialize(settingsItemJSON, OpenAISettings__c.class);
            update settingsItem;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}