force-app/main/default/objects/OpenAISettings__c/OpenAISettings__c.object-meta.xml
<CustomObject>
    <label>OpenAISettings</label>
    <nameField>
        <label>OpenAI Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpenAISettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenAISettings__c/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>/v1/completions</fullName>
                <default>true</default>
                <label>/v1/completions</label>
            </value>
            <value>
                <fullName>/v1/chat/completions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BaseURL__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text-davinci-003</fullName>
                <default>true</default>
                <label>text-davinci-003</label>
            </value>
            <value>
                <fullName>text-davinci-002</fullName>
            </value>
            <value>
                <fullName>text-curie-001</fullName>
            </value>
            <value>
                <fullName>text-babbage-001</fullName>
            </value>
            <value>
                <fullName>text-ada-001</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-0613</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k-0613</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Temperature</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChatGPTSettingsHandlerTest.cls
/****** BEGIN LICENSE BLOCK *****
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
The Initial Developer of the Original Code is Amberteq Inc.
Portions created by the Initial Developer are Copyright (C) 2023
the Initial Developer. All Rights Reserved.
***** END LICENSE BLOCK ******/

@isTest
public with sharing class ChatGPTSettingsHandlerTest {
    
    @isTest
    public static void testGetSettings() {
        OpenAISettings__c settingsItem = new OpenAISettings__c(Name = 'Settings', BaseURL__c = '/v1/chat/completions', Model__c = 'gpt-4');    
        insert settingsItem;

        OpenAISettings__c recievedSettingsItem = ChatGPTSettingsHandler.getSettings(UserInfo.getUserId());

        System.assertEquals(settingsItem.Id, recievedSettingsItem.Id);
    }

    @isTest
    public static void testGetSettingsWithNoSettingsRecord() {
        OpenAISettings__c recievedSettingsItem = ChatGPTSettingsHandler.getSettings(UserInfo.getUserId());

        System.assert(recievedSettingsItem.Id != null || recievedSettingsItem.Id != '');
    }

    @isTest
    public static void testUpdateSettings() {
        OpenAISettings__c settingsItem = new OpenAISettings__c(Name = 'Settings', BaseURL__c = '/v1/completions', Model__c = 'text-davinci-003');
        insert settingsItem;

        settingsItem.Temperature__c = 1.0;
        ChatGPTSettingsHandler.updateSettings(JSON.serialize(settingsItem));

        settingsItem = [SELECT Id, Temperature__c FROM OpenAISettings__c LIMIT 1];
        System.assertEquals(1.0, settingsItem.Temperature__c);
    }

}