force-app/main/default/objects/OpenAISettings__c/OpenAISettings__c.object-meta.xml
<CustomObject>
    <label>OpenAISettings</label>
    <nameField>
        <label>OpenAI Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpenAISettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenAISettings__c/fields/ChatHistory__c.field-meta.xml
<CustomField>
    <fullName>ChatHistory__c</fullName>
    <label>Chat History</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/DateToDeleteChatHistory__c.field-meta.xml
<CustomField>
    <fullName>DateToDeleteChatHistory__c</fullName>
    <label>Date To Delete Chat History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpenAISettings__c/fields/LengthOfDaysToKeepHistory__c.field-meta.xml
<CustomField>
    <fullName>LengthOfDaysToKeepHistory__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Length Of Days To Keep History</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Constants.cls
public with sharing class Constants {
    public static final String SETTINGS_ITEM_CHAT_INFO_QUERY = 'SELECT Id, ChatHistory__c, DateToDeleteChatHistory__c, LengthOfDaysToKeepHistory__c FROM OpenAISettings__c';
    public static final String SCHEDULE_TIME_BATCH = '0 00 00 * * ?';
    public static final String DELETE_CHAT_HISTORY_BATCH_JOB_NAME = 'ChatGPT Delete Chat History Batch Job';
    public static final String DELETE_CHAT_HISTORY_BATCH_JOB_TEST_NAME = 'ChatGPT Delete Chat History Batch Job from test';
    public static final String API_KEY_NAME = 'OpenAI API Key';
}